config/routes.rb
Rails.application.routes.draw do
  get '/help',to:'main_pages#help'

  get '/about',to:'main_pages#about'

  root 'main_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    #returns the full title on a per-page basis.
    def full_title (page_title = '')
        base_title = "ngaBandung"
        if page_title.empty?
            base_title
        else
            page_title + " || " + base_title
        end
    end
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Copyright 2017
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Help", help_path %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]-->
        <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js/"></script>
    <!--[endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/main_pages/_search_route.html.erb
<form action="#" method="get" autocomplete="on">
    <div id="place-start">
        <input type="text" name="place-start" placeholder="Asal" id="start">
        <button type="button" onclick="getLocation()">Bingung lagi dimana?</button>
    </div>
    <input type="text" name="place-finish" placeholder="Tujuan">
    <input type="submit" value="CARI">
</form>

app/views/main_pages/about.html.erb
<% provide(:title, "About") %>

<!--Inside of Body Tag-->
<h1>About</h1>
<p>
    The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
    Tutorial</em></a> is a
    <a href="http://www.railstutorial.org/book">book</a> and
    <a href="http://screencasts.railstutorial.org/">screencast series</a>
    to teach web development with
    <a href="http://rubyonrails.org/">Ruby on Rails</a>.
    This is the sample application for the tutorial.
</p>

<%= link_to "Back to Home", root_path %>

app/views/main_pages/help.html.erb
<% provide(:title, "Help") %>

<!--Inside of Body Tag-->
<h1>Help</h1>
<p>
    Get help on the Ruby on Rails Tutorial at the
    <a href="http://www.railstutorial.org/help">Rails Tutorial help
    page</a>.
    To get help on this sample app, see the
    <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
    Tutorial</em>
    book</a>.
</p>

<%= link_to "Back to Home", root_path %>

app/views/main_pages/home.html.erb
<h1>ngaBandung</h1>

<%= render 'main_pages/search_route' %>